trigger:
- master

pool:
  vmImage: ubuntu-latest

extends:
   template: build.generic.yml
   parameters:
     postBuildSteps: 
       - task: PublishPipelineArtifact@1
         displayName: Publish pipeline artifact 'todoItemsApi'
         inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)/todoItemsApi'
          artifact: 'todoItemsApi'
          publishLocation: 'pipeline'
