trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - .github/**
    - .devcontainer/**
    - .vscode/**

schedules:
- cron: "0 0 * * 3"
  always: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

extends:
   template: generic.yml
   parameters:
     bicepTemplate: main.docker.webapp.bicep
     bicepAdditionalParameters: '-dockerImageNameAndTag ghcr.io/maartenvandiemen/todoitems:$(Build.SourceVersion)'
     postBuildSteps: 
       - task: Docker@2
         inputs:
           containerRegistry: 'Github Packages'
           repository: $(Build.Repository.Name)
           ${{ if eq(variables['Build.Reason'], 'Manual') }}:
             command: 'buildAndPush'
           ${{ else }}:
             command: 'build'
           Dockerfile: '**/Dockerfile'
           buildContext: '$(Build.ArtifactStagingDirectory)/todoItemsApi'
           tags: '$(Build.SourceVersion)'
