parameters:
- name: dependsOn
  type: object

jobs:
- job: SmokeTests
  pool:
    vmImage: ubuntu-latest
  ${{ if parameters.dependsOn }}:
    dependsOn: ${{parameters.dependsOn}}
  variables:
  - name: appServiceUrl
    value: $[ dependencies.Create_Env.outputs['SaveDeploymentOutputs.appServiceAppUrl'] ]
  steps:
  - checkout: none
  - download: current
    artifact: smoketests
    displayName: Download smoketests
  - script: docker run --rm -v $(Pipeline.Workspace)/smoketests:/workdir jetbrains/intellij-http-client:latest test.http -V host=$(appServiceUrl)
    displayName: Run IntelliJ HTTP Client tests
