  trigger: none

pool:
  vmImage: windows-latest

resources:
  pipelines:
  - pipeline: webApp
    source: TodoItems.Build.NoDocker
    trigger: 
      branches:
      - main

stages:
 - stage: O
   jobs:
   - deployment:
     variables:
      - group: TodoItemsApi-O
     environment: TodoItem-O
     strategy:
      runOnce:
        deploy:
          steps:
            - download: webApp
              artifact: infraCode
              displayName: Download Bicep files
            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: 'MSN Azure'
                subscriptionId: '052513ff-2610-4a3d-a8b1-c17241db3e38'
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'BicepDemo'
                location: 'East US'
                templateLocation: 'Linked artifact'
                csmFile: '$(Pipeline.Workspace)/webApp/infraCode/main.nodocker.webapp.bicep'
                csmParametersFile: '$(Pipeline.Workspace)/webApp/infraCode/main.nodocker.webapp.parameters.json'
                overrideParameters: '-sqlAdministratorLoginPassword $(todoItemsSqlAdminpassword-O)'
                deploymentMode: 'Incremental'
              env:
                sqlAdministratorLoginPassword: $(todoItemsSqlAdminpassword-O)