trigger:
  branches:
    include:
    - master
    - main
  paths:
    exclude:
    - .github/**
    - .devcontainer/**
    - .vscode/**

schedules:
- cron: "0 0 * * 3"
  always: true
  branches:
    include:
    - main
    - master

pool:
  vmImage: ubuntu-latest

extends:
   template: generic.yml
   parameters:
     bicepTemplate: main.nodocker.webapp.bicep
     postBuildSteps: 
       - task: PublishPipelineArtifact@1
         displayName: Publish pipeline artifact 'todoItemsApi'
         inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)/todoItemsApi'
          artifact: 'todoItemsApi'
          publishLocation: 'pipeline'
