on:
  workflow_call:
    inputs:
      sqlServerFQDN:
        type: string
        required: true
        description: SQL Server Fully Qualified Domain Name
      databaseName:
        type: string
        required: true
        description: Databasename
    secrets:
      AZURE_SQL_USER:
        required: true
        description: username to login with on Azure SQL
      SA_PASSWORD:
        required: true
        description: password of the username to login with on Azure SQL
defaults:
  run:
    shell: pwsh
jobs:
  deploy_db:
    permissions: 
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment: AzureDeploy
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: database
          path: ${{github.workspace}}/artifacts/database
          
      - uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.3
        with:
          connection-string: 'Data Source=tcp:${{ inputs.sqlServerFQDN }},1433;Initial Catalog=${{ inputs.databaseName }};Persist Security Info=False;User Id=${{secrets.AZURE_SQL_USER}};Password=${{secrets.SA_PASSWORD}};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
          path: ${{github.workspace}}/artifacts/database/*.sql
