on:
  workflow_call: 
    inputs:
      webAppUrl:
        type: string
        required: true
        description: Name of the webbApp on which the tests need to be executed
defaults:
  run:
    shell: pwsh
jobs:
  smoke_tests:
    permissions:
      contents: read
      deployments: write
    runs-on: ubuntu-latest
    environment: AzureProvision
    steps:
      - name: Download test files
        uses: actions/download-artifact@v8
        with:
          name: smoketests
          path: ${{github.workspace}}/artifacts/smoketests

      - name: Execute IntelliJ HTTP Client tests
        run: docker run --rm -v ${{github.workspace}}/artifacts/smoketests:/workdir jetbrains/intellij-http-client:latest test.http -V host=${{inputs.webAppUrl}}
